name: Test Automation Workflow

on:
  schedule:
  - cron: 00 18 * * *
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Running Test Automation frame with Maven
      run: mvn test -X -Dbrowser=chrome -DisLambdaTest=true -DisHeadless=false

    - name: Upload Test logs
      if: always()
      uses: actions/upload-artifact@v4.6.2
      with:
         name: Test logs
         Path: logs/

    - name: Upload Screenshots as Artifacts
      if: always()
      uses: actions/upload-artifact@v4.6.2
      with:
         name: screenshots
         Path: screenshots/

    - name: Upload HTML Reports as Artifacts
      if: always()
      uses: actions/upload-artifact@v4.6.2
      with:
        name: html-Report
        Path: report.html

    - name: Test Execution status
      if: always()
      run: echo "Test Execution Completed"

    - name: Copy Report to github-pages Folder
      if: always()

      run:  |
        mkdir -p public/extents-reports 
        cp -R report.html  public/extent-reports/
        cp -R screenshots/  public/extent-reports/screenshots/
        ls -l
    - name: Deploy to GitHub Pages
      if: always()
      uses: JamesIves/github-pages-deploy-action@v4.7.3

      with:
        folder: public/extent-reports/
        token: ${{ secrets.PAT1234 }}
        clean: true
        
  
